### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ziad-saab**

### CODE REVIEW

**Comment by ajmas** [comment]
Could you also update:
- folder 'montreal/i/mentors/' with a photo, named ziad-saab.jpg
- file montreal/_config.yml with the appropriate information

Thanks

**Comment by ziad-saab** [comment]
@ajmas this PR was done on master instead of gh-pages. I'll make another one.

**Comment by ajmas** [comment]
You'll actually need this pull-request for the update of the readme.

**Comment by ziad-saab** [comment]
Thanks @ajmas  :))

**Pull request merged**
