### PR TITLE
[mentor]: add conan

### PR DESCRIPTION
**Pull request by aconanlai**

### CODE REVIEW

**Comment by matchai** [comment]
Hey Conan. Thank you for volunteering to join as a mentor! 👊 
Could you please add your name to `README.md` and add your picture to the images directory?

You can check out this earlier PR as an example: https://github.com/nodeschool/montreal/pull/105

Cheers! 👍

**Comment by aconanlai** [comment]
done!

**Comment by matchai** [comment]
Thank you for the update!
It looks like your addition to `_config.yml` is now missing, if you don't mind putting it back. 😅

**Comment by ajmas** [comment]
Image  looks broken on main website. Was it named correctly?

**Comment by matchai** [comment]
Whoops! You're right.
The name entered in `_config.yml` has to be the same as the image file name.
All of this should definitely be better documented. 😅

~~I'll revert it for the time being. Feel free to open a new PR fixing the issue @aconanlai.~~

I'll just push a fix directly. Sorry for the trouble.

**Pull request merged**
