### PR TITLE
Add Dec 4 Event

### PR DESCRIPTION
**Pull request by RichardLitt**
@ajmas I was unable to build - does this work?

### CODE REVIEW

**Comment by ajmas** [comment]
What issue are you running into? I'll wait for Travis to finish building and then I'll check.

**Comment by RichardLitt** [comment]
```
jekyll serve
/Users/richard/.rvm/gems/ruby-2.1.5/gems/bundler-1.16.0/lib/bundler/resolver.rb:288:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jekyll-multiple-languages-plugin' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
```

**Comment by ajmas** [comment]
You ran ```./script/cibuild```?

Also try `gem source -​-update` -> http://guides.rubygems.org/command-reference/#gem-sources

BTW Travis is happy and builds on my computer too. Oh, and I am using Ruby 2.4.2 and Travis is using Ruby 2.4.1

**Comment by ajmas** [comment]
Since it works for me and based on off thread conversation I'll accept PR.

**Pull request merged**
