### PR TITLE
[WIP] Implement i18n to support French page translations

### PR DESCRIPTION
**Pull request by matchai**
Heya! 👋
I've gone ahead and begun implementing i18n  to take care of #1, using [jekyll-multiple-languages-plugin](https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin). 🇨🇦

So far it's been smooth sailing until I realized that the checkout process is done using a widget.  After reading through the [docs to Tito](https://ti.to/docs/widget), it doesn't look like they've got support for i18n. It looks like you can however add an html attribute to the widget to show specific tickets.

@pcuci: Would you be able to add secondary tickets of each kind with a french label as well? We can filter out the English ones on French checkout and vice-versa.

I've also gone ahead and created a Gemfile to speed up initial setup, since we are adding more than a couple dependencies. Just so we use the correct version of Jekyll, can someone confirm if the live version of the site is the one being hosted on gh-pages? If so, I'll also include [pages-gem](https://github.com/github/pages-gem) as a dependency. 💎

I'm mostly done implementing translation tags throughout the index of the site. If anyone's got any feedback or suggestions as to how this can be done in a better/simpler/faster way, please let me know! 😀

### CODE REVIEW

**Comment by matchai** [comment]
As an added note, could one of the project managers [apply for a Crowdin license](https://crowdin.com/page/open-source-project-setup-request)? We could use the GitHub integration to have approved translations added to the project directly

**Comment by pcuci** [comment]
@matchai could you rebase and resend PR please?

Does github/pages-gem#401 block us? Re: #1

**Comment by matchai** [comment]
@pcuci That issue does block us as long as we don't have a CI system or a build process.
I can make us a gulp build and deploy process when I've got some free time.

**Comment by RichardLitt** [comment]
@matchai Any updates on this? :)

**Comment by matchai** [comment]
@RichardLitt  I was waiting to get github integration approved for the build and hosting platform you had suggested at a previous nodeschool meetup (who's name I can't remember off the top of my head).

**Comment by RichardLitt** [comment]
Probably Netlify?

**Comment by matchai** [comment]
That's the one! Since I'm not in the nodeschool org, I don't have the ability to configure the repo with Netlify. I had sent an email at the time asking for a hand, but I guess that's now long gone.

**Comment by RichardLitt** [comment]
>  I had sent an email at the time asking for a hand, but I guess that's now long gone.

I doubt anyone is watching the emails. Open an issue on the GitHub organization. That might help?

**Comment by ajmas** [comment]
I could look at a CI solution. The two I have played with recently are Travis and Circle CI, which both offer free solutions to public repos. They both have Github integrations.

**Comment by ajmas** [comment]
Have created issue #66 for CI support.

**Comment by ajmas** [comment]
Okay, went and completed the work for CI. I took the chance and made gh-pages-src the source branch for gh-pages, with Travis deploying to gh-pages branch. The changes here will need to be done agains the new branch. Hope that is okay.

**Pull request closed without merging**
