### PR TITLE
Spring cleaning (website refresh)

### PR DESCRIPTION
**Pull request by matchai**
Howdy NodeSchool team,

I've gone ahead and done what I had suggested in #76 and recreated our website, using NodeSchool Toronto's as a template.

This should address #76 and #78.

### CODE REVIEW

**Comment by ajmas** [comment]
Any reason for removing real names from the configuration?

Also concerned with deletion of the deploy_key.enc file which is necessary for the deployment to gh-pages

**Comment by ajmas** [comment]
We can merge this soon if no one objects. Worst case we roll back certain changes?

**Comment by matchai** [comment]
@ajmas Should we be concerned about "bad decrypt" on line 900 of the last build?

**Comment by matchai** [comment]
I don't appear to have access to assign a new deploy key to the repo, so I'll wait until it gets updated.

**Comment by ajmas** [comment]
@matchai only the the project account during merge to master has the right permissions, from what I remember. The deploy script is based on the gist here:

https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

You will see some stuff in the comments.

Additional points, following some testing:

  - Will have to fix the mentor layout algorithm, which got broken here
  - The 'Generating the Site' section is missing from the `contribution.md` document. I think it would be useful to keep, since it is is not clear otherwise how to build and test?
  - While running `bundle exec jekyll serve` I noticed a bunch of missing images from the `/i/photos/` directory, haven't investigated the cause.
  - The 'How do I install Node' FAQ entry seems very Mac specific, we should probably deal with this question in a multi-platform way --> I can open a specific ticket for this?

**Comment by matchai** [comment]
The mentors are appearing correctly for me. Could I see a screenshot of how it appears on your end?
I totally agree that the Node installation instructions aren't OS agnostic. A separate issue would make sense to address it.

**Comment by matchai** [comment]
Regarding the deploy process, the encrypted key doesn't appear to be able to be decrypted.
I don't have access to https://github.com/nodeschool/montreal/settings/keys, where the key is assigned.

**Comment by ajmas** [comment]
I imagine it is a question of preference, in terms of display, though the current live version was done so it didn't look unbalanced.

screen shot 2018-01-25 at 14 17 05
screen shot 2018-01-25 at 14 17 35

**Comment by matchai** [comment]
I think that's simply a matter of the sidebar's width. I don't think it was ever a deliberate decision to have it be full.
I think that would best be addressed as a separate issue.

**Comment by matchai** [comment]
I'll see if the correct permissions are applied when merging to master.
Here we go!

**Pull request merged**
