### PR TITLE
Fixed #79, adding OpenGraph metadata

### LINKED ISSUE #79: Add support for OpenGraph related metadata

### PR DESCRIPTION
**Pull request by ajmas**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Have you run this through the validators?

**Comment by RichardLitt** [comment]
Looks fine to me. We can fix it it doesn't work right.

**Comment by ajmas** [comment]
I hadn't, but this was essentially code I had used for another site, which did work. Any validators we can use?

**Comment by RichardLitt** [comment]
https://cards-dev.twitter.com/validator and https://developers.facebook.com/tools/debug/

**Pull request merged**
